require: rubocop-rspec

AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'vendor/**/*'
    - '**/spec_helper.rb'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - '**/*_spec.rb'
  ExcludedMethods:
    - 'describe'
    - 'context'

Metrics/LineLength:
  Enabled: true
  Max: 90

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
